### PR TITLE
Fix wingspan dependency

### PR DESCRIPTION
**Pull request by williamkunz**
Solves issue #2 and builds now

### CODE REVIEW

**Comment by williamkunz** [comment]
:+1: 
Thanks for sharing.

**Comment by dustingetz** [comment]
I actually don't think this project explicitly depends on react-cursor - but it does take a prop which it assumes is a react-cursor. I don't think it's necessary to build this library.

Coincidentally, this project is probably about to get some love in the next week or two.

**Comment by williamkunz** [comment]
I'm going to be converting it to a CommonJS build if that helps any

**Comment by dustingetz** [comment]
It does, thanks

**Pull request merged**
